apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: 'https://github.com/aniketgh5/employee-management-system-aks.git'
    targetRevision: main
    path: aks

  destination:
    server: https://kubernetes.default.svc
    namespace: employee-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
